In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
# Cargamos el archivo CSV
data = pd.read_csv("Citas_Digital_Filtrado.csv")

# Visualizamos las primeras filas
data.head()

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...

In [9]:
#Identificar valores nulos por columna
valores_nulos=data.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [10]:
#Identificar valores nulos por dataframe
valores_nulos=data.isnull().sum().sum()
valores_nulos

np.int64(3557)

In [11]:
# Realizamos una copia del dataframe
data2 = data.copy()

data2.head()

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...

# BDC — reemplazar con la moda

# BDC es una variable categórica, por lo que podemos reemplazar los nulos por el valor que aparece con mayor frecuencia.

In [15]:
# Sustituir valores nulos de BDC con la moda
moda_bdc = data["BDC "].mode()[0]

data2["BDC "] = data2["BDC "].fillna(moda_bdc)

In [ ]:
#VERIFICAMOS SI FUNCIONO
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

En la variable BDC se identificaron 16 valores nulos. Debido a que es una variable categórica, se decidió sustituir los valores faltantes utilizando la moda, es decir poner un valor con mayor frecuencia en la columna. En este caso, la moda fue “Ana”, por lo que los valores nulos se reemplazaron con este dato. Esta técnica  permite completar la información manteniendo la categoría más representativa de la variable.

# Fecha — imputación basada en el contexto o por grupos.

In [51]:
# Reemplazar valores nulos de Fecha de acuerdo con el mes correspondiente

# Imputación de Fecha por contexto / bloques mensuales

data2.loc[0:32, "Fecha"] = data2.loc[0:32, "Fecha"].fillna("Abril 2025")
data2.loc[33:59, "Fecha"] = data2.loc[33:59, "Fecha"].fillna("Mayo 2025")
data2.loc[60:86, "Fecha"] = data2.loc[60:86, "Fecha"].fillna("Junio 2025")
data2.loc[87:120, "Fecha"] = data2.loc[87:120, "Fecha"].fillna("Julio 2025")
data2.loc[121:166, "Fecha"] = data2.loc[121:166, "Fecha"].fillna("Agosto 2025")
data2.loc[167:230, "Fecha"] = data2.loc[167:230, "Fecha"].fillna("Septiembre 2025")
data2.loc[231:290, "Fecha"] = data2.loc[231:290, "Fecha"].fillna("Octubre 2025")
data2.loc[291:343, "Fecha"] = data2.loc[291:343, "Fecha"].fillna("Noviembre 2025")
data2.loc[344:391, "Fecha"] = data2.loc[344:391, "Fecha"].fillna("Diciembre 2025")

data2.loc[392:428, "Fecha"] = data2.loc[392:428, "Fecha"].fillna("Enero 2026")
data2.loc[429:460, "Fecha"] = data2.loc[429:460, "Fecha"].fillna("Febrero 2026")
data2.loc[461:477, "Fecha"] = data2.loc[461:477, "Fecha"].fillna("Marzo 2026")
data2.loc[478:538, "Fecha"] = data2.loc[478:538, "Fecha"].fillna("Abril 2026")
data2.loc[539:598, "Fecha"] = data2.loc[539:598, "Fecha"].fillna("Mayo 2026")
data2.loc[599:640, "Fecha"] = data2.loc[599:640, "Fecha"].fillna("Junio 2026")
data2.loc[641:675, "Fecha"] = data2.loc[641:675, "Fecha"].fillna("Julio 2026")

In [52]:
#VERIFICAMOS SI FUNCIONO
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Telefono                                    0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         0
SDC                                         0
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

In [21]:
data2.head()

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,Abril 2025,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,Abril 2025,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,Abril 2025,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,Abril 2025,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,Abril 2025,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...

Se utilizó esta técnica porque los registros de la base de datos están organizados por bloques correspondientes a cada mes. Por lo tanto, los valores nulos de la variable Fecha fueron reemplazados con el mes y año del bloque al que pertenece cada registro. Esta técnica permite completar los datos sin inventar un día específico que no está disponible en la información original.

# Nombre Cliente — string específico

In [23]:
data2["Nombre Cliente "] = data2["Nombre Cliente "].fillna(
    "Cliente no registrado"
)

In [24]:
#VERIFICAMOS SI FUNCIONO
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         2
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

En la variable Nombre Cliente se identificaron 21 valores nulos. Se decidió reemplazarlos por el texto “Cliente no registrado”, ya que no es posible determinar el nombre real. No se utilizó la moda ni métodos de propagación porque podrían asignar incorrectamente el nombre de otro cliente al registro.

# Telefono — string específico

In [26]:
data2["Telefono "] = data2["Telefono "].fillna(
    "Telefono no registrado"
)

In [27]:
#VERIFICAMOS SI FUNCIONO
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         2
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

Se decidió reemplazarlos por el texto “Teléfono no registrado”, ya que no es posible inferir correctamente el número telefónico de un cliente a partir de otros registros.

# Estatus de Lead — imputación por moda

In [28]:
moda_estatus = data["Estatus de Lead"].mode()[0]

data2["Estatus de Lead"] = data2["Estatus de Lead"].fillna(
    moda_estatus
)

In [29]:
#VERIFICAMOS SI FUNCIONO
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         2
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

Debido a que se trata de una variable categórica, se utilizó la moda para reemplazar los datos faltantes. La categoría que apareció con mayor frecuencia fue “Activo”, por lo que se asignó este valor a los registros nulos. Esta técnica permite conservar la categoría más representativa dentro de la variable.

# Potencial de compra — imputación por mediana

In [30]:
potencial_numerico = pd.to_numeric(
    data["Potencial de compra"],
    errors="coerce"
)

potencial_numerico.median()

np.float64(0.75)

In [31]:
mediana_potencial = potencial_numerico.median()

data2["Potencial de compra"] = data2["Potencial de compra"].fillna(
    mediana_potencial
)

In [32]:
#VERIFICAMOS SI FUNCIONO
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         2
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

Se decidió utilizar la mediana de los valores numéricos válidos, la cual fue de 0.75, ya que esta medida permite sustituir los datos faltantes sin verse tan afectada por valores atípicos o posibles errores de captura. De esta manera se conserva un valor representativo de la distribución de la variable.

# PDM — imputación por moda

In [39]:
moda_pdm = data["PDM"].mode()[0]

moda_pdm

np.float64(0.0)

In [40]:
#VERIFICAMOS SI FUNCIONO
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         2
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

Debido a que esta variable es binaria , se decidió utilizar la moda.  No se utilizó la media debido a que podría generar valores decimales que no corresponden con las categorías posibles de la variable.

# SDC — imputación por moda

In [41]:
moda_sdc = data["SDC"].mode()[0]

moda_sdc

np.float64(0.0)

In [42]:
#VERIFICAMOS SI FUNCIONO
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         2
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

Debido a que esta variable es binaria , se decidió utilizar la moda.  No se utilizó la media debido a que podría generar valores decimales que no corresponden con las categorías posibles de la variable.

# Venta — imputación por moda

In [37]:
moda_venta = data["Venta"].mode()[0]

data2["Venta"] = data2["Venta"].fillna(moda_venta)

In [38]:
#VERIFICAMOS SI FUNCIONO
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         2
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

Debido a que esta variable es binaria y únicamente representa si hubo o no una venta mediante los valores 0 y 1, se decidió utilizar la moda.  No se utilizó la media debido a que podría generar valores decimales que no corresponden con las categorías posibles de la variable.

# Asesor asignado — imputación por valor constante

In [43]:
data2["Asesor Asignado"] = data2["Asesor Asignado"].fillna(
    "Sin asesor asignado"
)

In [44]:
#VERIFICAMOS SI FUNCIONO
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         2
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

 Se decidió sustituirlos por el texto “Sin asesor asignado”, ya que no es posible determinar con certeza qué asesor correspondía a cada registro. Aunque la variable es categórica, utilizar la moda podría asignar incorrectamente el asesor más frecuente a clientes que no necesariamente le pertenecen.

# Potencial de compra — imputación por valor constante

In [45]:
# Sustituir valores nulos de las preguntas abiertas

columnas_preguntas = [
    "¿Por que no ha visitado la agencia?",
    "¿Por que no hay solicitud de credito?",
    "¿Por que no hubo prueba de manejo ?",
    "¿Por que no hubo proceso wow?",
    "¿Por que se asigno antes de vistar piso?"
]

data2[columnas_preguntas] = data2[columnas_preguntas].fillna(
    "Sin informacion registrada"
)

In [46]:
# Corroborar valores nulos
valores_nulos = data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         2
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?         0
¿Por que no hubo prueba de manejo ?           0
¿Por que no hubo proceso wow?                 0
¿Por que se asigno antes de vistar piso?      0
Unnamed: 15                                 660
dtype: int64

Las variables correspondientes a los motivos por los que el cliente no realizó alguna etapa del proceso contienen respuestas cualitativas y específicas para cada caso. Por ello, los valores nulos fueron sustituidos por “Sin información registrada”, ya que utilizar moda, ffill o bfill podría asignar a un cliente una respuesta que en realidad corresponde a otro. De esta manera se conserva el registro sin generar información inexistente.

In [47]:
# Eliminar columna innecesaria
data2 = data2.drop(["Unnamed: 15"], axis=1)

Se decidió eliminar la variable Unnamed: 15 debido a que no cuenta con un nombre o significado definido dentro de la base y presenta una gran cantidad de valores nulos. Al no aportar información relevante para el análisis, se consideró una columna innecesaria.

In [53]:
# Corroborar valores nulos por columna
valores_nulos = data2.isnull().sum()
valores_nulos

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Telefono                                    0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         0
SDC                                         0
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

In [54]:
# Corroborar valores nulos en todo el dataframe
valores_nulos_total = data2.isnull().sum().sum()
valores_nulos_total

np.int64(0)

In [55]:
data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       676 non-null    str
 1   Fecha                                     676 non-null    str
 2   Nombre Cliente                            676 non-null    str
 3   Telefono                                  676 non-null    str
 4   Estatus de Lead                           676 non-null    str
 5   Potencial de compra                       676 non-null    object
 6   PDM                                       676 non-null    float64
 7   SDC                                       676 non-null    float64
 8   Venta                                     676 non-null    float64
 9   Asesor Asignado                           676 non-null    str
 10  ¿Por que no ha visitado la agencia?       676 non-null    str
 11  ¿Por que no hay solicitud de credito?     676 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       676 non-null    str
 13  ¿Por que no hubo proceso wow?             676 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  676 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 79.3+ KB

In [56]:
# Convertir DataFrame sin valores nulos a CSV
data2.to_csv("Citas_Digital_Sin_Nulos.csv", index=False)